# Generated by Django 4.1.3 on 2022-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(verbose_name='course_id')),
                ('course_title', models.CharField(max_length=300, verbose_name='course_title')),
                ('course_instructor', models.CharField(max_length=300, verbose_name='course_instructor')),
                ('course_capacity', models.IntegerField(verbose_name='course_capacity')),
                ('course_openseats', models.IntegerField(verbose_name='course_openseats')),
            ],
        ),
    ]
