# Generated by Django 2.2.5 on 2022-11-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
