# Generated by Django 4.1.3 on 2022-11-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Streamid', models.IntegerField(verbose_name='StreamID')),
                ('Streamtitle', models.CharField(max_length=230, verbose_name='StreamTitle')),
                ('Streaminstructor', models.CharField(max_length=170, verbose_name='StreamInstructor')),
                ('Streamcapacity', models.IntegerField(verbose_name='StreamCapacity')),
                ('StreamopenSeats', models.IntegerField(verbose_name='StreamOpenseats')),
            ],
        ),
    ]
