# Generated by Django 4.1.3 on 2022-11-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujectid', models.IntegerField(verbose_name='sujectid')),
                ('sujecttitle', models.CharField(max_length=200, verbose_name='sujecttitle')),
                ('sujectinstructor', models.CharField(max_length=200, verbose_name='sujectinstructor')),
                ('sujectcapacity', models.IntegerField(verbose_name='sujectcapacity')),
                ('sujectopenseats', models.IntegerField(verbose_name='sujectopenseats')),
            ],
        ),
    ]
