# Generated by Django 4.1.3 on 2022-11-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='sujectcapacity',
            field=models.IntegerField(verbose_name='subjectcapacity'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sujectid',
            field=models.IntegerField(verbose_name='subjectid'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sujectinstructor',
            field=models.CharField(max_length=200, verbose_name='subjectinstructor'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sujectopenseats',
            field=models.IntegerField(verbose_name='subjectopenseats'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sujecttitle',
            field=models.CharField(max_length=200, verbose_name='subjecttitle'),
        ),
    ]
